# Generated by Django 6.0.4 on 2026-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='calories_consumed',
            field=models.FloatField(default=0),
        ),
    ]
