# Generated by Django 6.0.4 on 2026-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_food_date_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.FloatField(default=100),
        ),
    ]
