# Generated by Django 6.0.4 on 2026-04-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_food_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Chicken Breast', 'Chicken Breast'), ('Egg', 'Egg'), ('Milk', 'Milk'), ('Banana', 'Banana'), ('Apple', 'Apple'), ('Bread', 'Bread')], max_length=100),
        ),
    ]
