# Generated by Django 6.0.4 on 2026-04-25 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_food_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
