# Generated by Django 6.0.4 on 2026-04-25 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_food_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
