# Generated by Django 6.0.4 on 2026-04-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_dailystats_date_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.FloatField(default=0),
        ),
    ]
