# Generated by Django 5.2.2 on 2026-04-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_food_carbs_food_fats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='calories_burned',
            new_name='calories',
        ),
    ]
