# Generated by Django 6.0.4 on 2026-04-28 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_calories_burned_workout_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='date_set',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='target',
            new_name='start_weight',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
