# Generated by Django 6.0.4 on 2026-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_date_set_goal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('gym', 'Gym'), ('yoga', 'Yoga'), ('football', 'Football'), ('cricket', 'Cricket')], max_length=50),
        ),
    ]
