# Generated by Django 6.0.4 on 2026-04-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_workout_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='sleep',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='water',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
