# Generated by Django 6.0.4 on 2026-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_dailystats_sleep_dailystats_water_dailystats_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='sleep_goal',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='step_goal',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='water_goal',
            field=models.FloatField(default=3.0),
        ),
    ]
